### PR TITLE
Fixed experiment sizes for orbital science

### PR DESCRIPTION
**Pull request by SirMortimer**
Support/OrbitalScience.cfg wasn't working. Also, it missed the FOR[Kerbalism] instruction.

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
Somewhere in the forum was a post about that a few weeks ago, it suggested to change that config to
```
// tweak DMagic Orbital Science experiments data size

@EXPERIMENT_DEFINITION[*]:HAS[#id[magScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]           { @dataScale = 30  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[rpwsScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]          { @dataScale = 33  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[scopeScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]         { @dataScale = 90  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmImagingPlatform]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism] { @dataScale = 135 }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmSIGINT]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]          { @dataScale = 50  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmReconScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]       { @dataScale = 38  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmNAlbedoScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]     { @dataScale = 55  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmXRayDiffract]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]    { @dataScale = 45  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmlaserblastscan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]  { @dataScale = 81  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmSolarParticles]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]  { @dataScale = 32  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmSoilMoisture]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]    { @dataScale = 28  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmAsteroidScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]    { @dataScale = 75  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmRadiometerScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]  { @dataScale = 49  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmseismicHammer]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]   { @dataScale = 29  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmbathymetryscan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]  { @dataScale = 18  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[dmbiodrillscan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]    { @dataScale = 88  }
@EXPERIMENT_DEFINITION[*]:HAS[#id[AnomalyScan]]:NEEDS[DMagicOrbitalScience,FeatureScience]:AFTER[zzzKerbalism]       { @dataScale = 42  }

```
But this could be the better method ...

**Comment by SirMortimer** [comment]
I didn't know about the forum post, I was just tinkering with it because I noticed the data rates are way to low. Then I found how it's done in System/Science.cfg, compared that to Support/OrbitalScience.cfg, and noticed one major difference:

System/Science.cfg does not have the [*] in the EXPERIMENT_DEFINITION. I removed that, added FOR[Kerbalism] for good measure and that seems to do the trick.

**Comment by steamp0rt** [comment]
Is this ready

**Comment by SirMortimer** [comment]
This is WOMM* certified, barring any objections I'd say it is ready.

* Works On My Machine

**Pull request merged**
