### PR TITLE
Connections

### PR DESCRIPTION
**Pull request by HaullyGames**
Automation - Remove legacy modules.
RemoteTech - Fix energy consumption for unloaded vessels.

### CODE REVIEW

**Comment by madman2003** [comment]
@HaullyGames does the removal of legacy fix anything besides dead code?

**Comment by HaullyGames** [comment]
No, just removing dead code.

**Comment by madman2003** [comment]
@HaullyGames is the 25 W/s synced up with planner?

`		void Process_rtantenna(PartModule m)
		{
			switch (m.moduleName)
			{
				case "ModuleRTAntennaPassive":
					Resource("ElectricCharge").Consume(0.0005, "communications (control)");   // 3km range needs approx 0.5 Watt
					break;
				case "ModuleRTAntenna":
					Resource("ElectricCharge").Consume(m.resHandler.inputResources.Find(r => r.name == "ElectricCharge").rate, "communications (transmitting)");
					break;
			}
		}`

**Comment by HaullyGames** [comment]
No sure, this is old staff that I forgot when I was fixing RT modules.
I haven't work on the Planner for a while

**Comment by madman2003** [comment]
> No sure, this is old staff that I forgot when I was fixing RT modules.
> I haven't work on the Planner for a while

That quoted piece of code was from the planner, should be ok, still might be wise to be familiar with the planner :-P

**Comment by HaullyGames** [comment]
I'm familiar with planner, I just haven't work on it those last updates.
:-P

**Comment by steamp0rt** [comment]
Tell me when ready

**Comment by HaullyGames** [comment]
It is ready.

**Pull request merged**
