### PR TITLE
Simulator updates needed for near future electrical

### PR DESCRIPTION
**Pull request by madman2003**
This is all of the work for done to simulator.
This supports per part resources in case they are non-flowable.

### CODE REVIEW

**Comment by madman2003** [comment]
@PiezPiedPy I did a split in two parts

**Comment by madman2003** [comment]
@PiezPiedPy i still would like to know what exactly you're expecting with regards to comments above functions

**Comment by PiezPiedPy** [comment]
@madman2003 I've just posted to the closed PR, hope it explains

**Comment by PiezPiedPy** [comment]
https://github.com/steamp0rt/Kerbalism/pull/274/files/7b7902af4518904e03d4c47d605b7b1f1e67deae#r230591741

**Comment by madman2003** [comment]
@PiezPiedPy @Gordon-Dry @steamp0rt I'm not expecting to do anything on this anymore ;-)

**Pull request merged**
