### PR TITLE
Don't show sickbay modules in automation if module has no capacity

### PR DESCRIPTION
**Pull request by SirMortimer**

### CODE REVIEW

**Comment by madman2003** [comment]
@SirMortimer why doesn't the sickbay have a normal on/off button?

**Comment by Gordon-Dry** [comment]
Yeah, the TV running all the time. In every bigger habitat.
And just-in-case the anti-radiation units are also online all the time ...

It's cheaper to check for the stress/radiation levels of the crew members who enter the habitat.
But less sophisticated.

And a button would be - retro. But helpful.

**Comment by steamp0rt** [comment]
Fix conflicts and i'll merge

**Comment by MartinDomig** [comment]
There should be an off option - worked for me. If it isn't there, that's a bug.

**Comment by madman2003** [comment]
@MartinDomig confusing bit is that the sickbay module is behind a part upgrade (which is off in sandbox by default)

**Comment by madman2003** [comment]
@SirMortimer have you abandoned this?

**Comment by steamp0rt** [comment]
F

**Pull request closed without merging**
