### PR TITLE
Better SSPX support:

### PR DESCRIPTION
**Pull request by doktorjet**
1) Balanced SSPX greenhouses to be twice as efficient as Kerbalism greenhouse. See [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/172400-131145-kerbalism-v180/&page=32&tab=comments#comment-3446891) for details.
2) Added missing exercise equipment for PXL-E 'Mercury', PXL-F 'Pilgrim' and PFD-C 'Coriolis'.
3) Fixed modulemanager syntax for sspx-utility-125-1 nerf patch. "@" is for editing existing values. No prefix is for adding new ones.

### CODE REVIEW

**Comment by PiezPiedPy** [comment]
Please discus on the Discord

**Comment by PiezPiedPy** [comment]
@steamp0rt hold off on this merge until things are resolved.

**Comment by steamp0rt** [comment]
K

**Comment by doktorjet** [comment]
I believe, things are resolved. He assumed that all free space will be stucced with hydroponic shelves, ignoring the greenhouse models themself. Models clearly show what grows where.

BTW, made a slapdash draft model to show @PiezPiedPy how growing sections can be effectively arranged in zero-g. https://imgur.com/a/jTb4Kl4

**Comment by PiezPiedPy** [comment]
Not really, I've not had a chance to study the BIOS-3 documentation yet so we can agree on the values used 😉

**Comment by doktorjet** [comment]
[More info](https://forum.kerbalspaceprogram.com/index.php?/topic/172400-131145-kerbalism-v180/&do=findComment&comment=3447354).
With detailed BIOS-3 documentation we have exactly the stats I propose... and even with 40% reserve.

**Comment by PiezPiedPy** [comment]
After reading and also looking into the 1/4 scale issue I have to agree but if the scale stays 1:1 then we have a problem whereas the greenhouses including Kerbalisms will actually be 4x too small. 🙄

**Comment by PiezPiedPy** [comment]
@doktorjet Just a heads up that if PR #194 goes ahead then rates in this PR will need to be adjusted to keep the 200% ratio otherwise SSPX greenhouses will end up having an 800% rate increase if PR #194 Is merged.
Also could you add a short description of your changes to the Changelog.md file 😉

**Comment by doktorjet** [comment]
Will update if TAC LS rates are implemented. Now waiting.

**Comment by doktorjet** [comment]
Updated and ready to merge.

**Pull request merged**
