### PR TITLE
Sickbay additions

### PR DESCRIPTION
**Pull request by Gordon-Dry**
Changed the patch for adding _SickbayTV:
Now only crewable parts with a CrewCapacity > 3 AND without the modules !MODULE[ModuleCommand],!MODULE[Laboratory],!MODULE[StationScienceModule],!MODULE[LaunchClamp] get the TV.
The patch also is changed to AFTER[zzzKerbalism] to not overlook the module check.

Support:
Three parts get the _SickbayRDU:
Bluedog_DB
MOL Orbital Habitation Segment (3 crew, no lab)
SSPX:
PTD-5 'Sunrise' Habitation Module (2 crew, no lab)
NearFutureSpacecraft:
PPD-24 Itinerant Service Container (2 crew, no lab)

I changed the sickbay TV to only use 1.2 EC/s instead of 12 EC/s - discuss it.

Because I was lazy to open another branch + PR I added some text to the habitat.rst

### CODE REVIEW

**Comment by theJesuit** [comment]
Can you not pilot a vehicle and watch TV at the same time :) ?  Jks.

Agrees.   Are sick bay and tv still both available in hitchhiker?

**Comment by Gordon-Dry** [comment]
Yes

**Comment by Gordon-Dry** [comment]
From my side this can be merged.

Some discussion about the EC/s still needed??

**Comment by madman2003** [comment]
@Gordon-Dry 1.2 kW for a TV is still insane, 100W (i.e. 0.1EC/s) would be more like it
But probably the effect should be nerfed to remain reasonable

**Comment by Gordon-Dry** [comment]
I know - but I would like to see you fight each other than letting me finally decide how much EC/s is appropriate.

1. I didn't create the sickbay
2. I didn't decide about the EC/s initially

**Comment by Gordon-Dry** [comment]
But okay, my first idea after I have seen the values was this:
TV 0.25
RDU 3.5

I will just push it and see how the reactions are ...

**Comment by Gordon-Dry** [comment]
And now?

**Comment by Gordon-Dry** [comment]
What do I know, these are not "my" numbers, I just changed them.
And I already nerfed them down - and they're still too high.

**Comment by Gordon-Dry** [comment]
Updated.

**Comment by steamp0rt** [comment]
Ready/

**Comment by Gordon-Dry** [comment]
That was a question?

Yes, ready.

**Pull request merged**
