### PR TITLE
UI scaling improvements

### PR DESCRIPTION
**Pull request by madman2003**
I have a high DPI screen and I can barely read the Kerbalism UI, this is a big improvement over that, where 150% scaling actually works.

### CODE REVIEW

**Comment by madman2003** [comment]
FYI, this doesn't make everything 100% perfect, I couldn't fix the "comforts" tooltip to be perfect. Some text will slightly misalign on 150%, like this:
bla      bla
bla   wrong alignment
bla      bla

**Comment by madman2003** [comment]
Sorry, I missed two things. The UI has been tiny for so long, that I didn't know what to look for :-P

**Comment by steamp0rt** [comment]
take a pic when you're done

**Comment by madman2003** [comment]
This is 170% scaled UI, showing the misalignment I mentioned that I could not fix (without making changes I cannot oversee).

image

**Comment by madman2003** [comment]
The overlap with Kerbal Engineer is something I only just fully realized now.
Have to see if the UI can made less wide without affecting the normal scale behavior.

image
image
image

**Comment by madman2003** [comment]
After change:

image
image
image
image

**Comment by steamp0rt** [comment]
Tell me when this is done and ready 👍

**Comment by madman2003** [comment]
@steamp0rt I'm happy with it, if you are too, then merge ;-)

**Comment by steamp0rt** [comment]
Ok

**Pull request merged**
