### PR TITLE
Near future attempt 2

### PR DESCRIPTION
**Pull request by madman2003**
This includes all commits from here https://github.com/steamp0rt/Kerbalism/pull/280, please merge that one first.

### CODE REVIEW

**Comment by madman2003** [comment]
@PiezPiedPy I did a split in two parts

**Comment by madman2003** [comment]
@PiezPiedPy @Gordon-Dry @steamp0rt I'm not expecting to do anything on this anymore ;-) Beware that https://github.com/steamp0rt/Kerbalism/pull/280 is a hard precondition for this one, and i obviously tested the combination.

**Comment by madman2003** [comment]
the files are completely orthogonal (#280 is code, #281 is config files)

**Comment by steamp0rt** [comment]
Fix conflicts

**Pull request merged**
