### PR TITLE
RemoteTech Update

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Too much to list.
Will need testing by others before release to make sure all bugs are squashed.

I've also tested on KSP1.3.1 and seems to be fine.

### CODE REVIEW

**Comment by steamp0rt** [comment]
I absolutely do not like the idea of requiring a custom RT DLL.

TRY to patch RemoteTech at runtime ffs

**Comment by PiezPiedPy** [comment]
Fuck You with ffs, I've spent over 5 days on this, you asked me to fix it, I did, do it your fucking self next time.

**Comment by PiezPiedPy** [comment]
Here you go https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/754

**Comment by steamp0rt** [comment]
OF FUCKING COURSE IT CAN'T BE PATCHED. GUESS WE'LL NEED TO WAIT FOR TAXISERVICE TO ACCEPT THE PR, SINCE HE DID SAY HE WAS WORKING ON IT

😦 🔫

**Comment by steamp0rt** [comment]
STUPID FUCKING SJW GITHUB REPLACING THE GUN EMOJI SO I CAN'T PROPERLY REPRESENT HOW FUCKING SAD I FEEL SOMETIMES

GITHUB IS RUN BY A BUNCH OF DUMBFUCK SJWS. I SAW SOMEONE GET SUSPENDED FOR SAYING "RETARD" OR SOMETHING ONE TIME. FUCK YOU, STEP ON A LEGO, GITHUB!

**Comment by PiezPiedPy** [comment]
Lol `STEP ON A LEGO` 🤣 Love it

**Comment by PiezPiedPy** [comment]
For those willing to test this PR. Here is a pre-release of RT's dll and a debug version of Kerbalism's dll

[RT PR Test.zip](https://github.com/steamp0rt/Kerbalism/files/2282732/RT.PR.Test.zip)

**Pull request merged**
