### PR TITLE
Refresh CommNet status of unloaded vessels

### LINKED ISSUE #212: Connected State not Updated in Background
Using stock CommNet, the connected/unconnected status of unloaded vessels is innacurate. There seems to be two separate issues:
1. Unloaded vessels keep their current signal status until a scene change or until the vessel is selected/highlighted in the tracking station, this issue happens at the KSC, tracking station, and when a different vessel is loaded
2. Vessels without a connection will gain one (according to Kerbalism) if they are unloaded by going directly to the tracking station

This does not impact vessels that are loaded in the foreground, nor does it impact the CommNet lines drawn by KSP.

This issue could be related to #133.

Kerbalism 1.9.1 build 135 & dependencies only
KSP 1.4.5 x64 on Windows

### PR DESCRIPTION
**Pull request by leomike**
Code based off @HaullyGames's work. Resolves #212.

### CODE REVIEW

**Comment by HaullyGames** [comment]
Wow, you found it.
I knew that I had fixed this issue before, but I'm stuck in Habitat equalize process for now.
Thanks man.

**Comment by PiezPiedPy** [comment]
Sweet 😃 
🍺 🍺 for you

**Comment by HaullyGames** [comment]
Could you please check the performance with more than 5 vessels? (I have no time now)

Create some ships and send them to different places, then launch a ship (airplane or rocket), after that, do maneuvers that create a lot of force G
Until I remember, this solution had performance issue when you have 5 or more vessels (NetworkUpdate does many loops and math calculations)

**Comment by SirMortimer** [comment]
If you call this when avessel goes lut of ec that could maybe solve #133

**Comment by PiezPiedPy** [comment]
#133 was fixed a while ago ?

**Comment by SirMortimer** [comment]
that was RT. but I didn’t verify, might well be that commnet behaves differently now

**Comment by leomike** [comment]
@PiezPiedPy Took me longer to figure out than it should, but ConnectionInfo only gets called when a vessel is cleared from Cache, effectively recalculating only one vessel per Update tick, so moving it to Kerbalism.Update probably doesn't makes sense.

The current method does introduce a lag as we don't ask CommNet to recalculate a vessels connectivity, but rather set a flag for CommNet to do so. Given the flag is set as the Cache for the vessel is recreated, this would not take effect until the next time the cache for this vessel is cleared. Overall this shouldn't affect the average duration a vessel is considered connected, but rather only impact when it is seen as connected (at 1x or with low vessel count this isn't a large issue, at larger time warp with high vessel count, a user looking at the map might notice the lag).

**Comment by PiezPiedPy** [comment]
A laggy update for a connection detection is better than no detection at all though.

@steamp0rt I think this should be merged.

**Comment by steamp0rt** [comment]
ok

**Comment by leomike** [comment]
I would expect CommNet to be disabled in the settings if RemoteTech is used, so this code shouldn't even be run. Could still try moving the code to be inside the "if(v.connection != null)" which it probably should have been in the first place anyways which would solve any potential error caused by this change.

**Comment by Gordon-Dry** [comment]
CommNet will be automatically disabled when RemoteTech is active - as long this is not overwritten in a RemoteTech cfg file manually.
It is disabled on my end.

This is a wild guessing, but two days ago I first recognized weird issues in Kerbalism and try to pinpoint as far as I can ...

Reached SPC and already got spammed the log (and icon missing):
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

It continues in VAB, but different message:
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

```
^repeats

And on launchpad:
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```
quote steamport:

> the problem appears to be occuring in Vessel_info
> but maybe
> Ok
> I see
> probably is related
> Probably this:
> ((KCommNetVessel) v.connection).forceUpdateUnloaded();
> Try compiling Kerbalism with line 170 in ConnectionInfo.cs commented out

**Comment by Gordon-Dry** [comment]
I see, line 81 ...

**Comment by leomike** [comment]
@Gordon-Dry Can you test with the change steamp0rt suggested or with the attached dll. This should at least solve the null errors in ConnectionInfo.

[Kerbalism.zip](https://github.com/steamp0rt/Kerbalism/files/2454275/Kerbalism.zip)

**Comment by Gordon-Dry** [comment]
@leomike I will do.

**Pull request merged**
